  CREATE TABLE ATTENDANCE
   (ATTENDANCE_DATE DATE,
    ATTENDANCE_SEQ NUMBER(11), 
    ATTENDANCE_TYPE NUMBER(2) NOT NULL,
    ATTENDANCE_STATUS NUMBER(2) DEFAULT 0 NOT NULL,
    USER_CD VARCHAR2(10),
    ATTENDANCE_REG_DATE TIMESTAMP DEFAULT SYSDATE,
    ATTENDANCE_UPD_DATE TIMESTAMP,
    ATTENDANCE_DEL_DATE TIMESTAMP,
    ATTENDANCE_UPD_CNT NUMBER(10) DEFAULT 0,
    ATTENDANCE_DEL_CNT NUMBER(10) DEFAULT 0,
    LATITUDE VARCHAR2(20),
    LONGITUDE VARCHAR2(20),
    PLACE_INFO VARCHAR2(70),
    TERMINAL VARCHAR2(10),
    ERROR_CD VARCHAR2(30),
    ERROR_MSG VARCHAR2(100),
    REMARK VARCHAR2(300),
    REGIST_USER VARCHAR2(10), 
    REGIST_DATE DATE DEFAULT SYSDATE, 
    UPDATE_USER VARCHAR2(10), 
    UPDATE_DATE DATE DEFAULT SYSDATE, 
    UPDATE_CNT NUMBER(10,0) DEFAULT 0, 
    DEL_FLG VARCHAR2(1) DEFAULT '0',
   CONSTRAINT ATTENDANCE_PK PRIMARY KEY (ATTENDANCE_DATE, ATTENDANCE_SEQ, USER_CD),
   CONSTRAINT USER_MST_FK FOREIGN KEY (USER_CD) REFERENCES USER_MST(USER_CD) ON DELETE CASCADE
  );

   COMMENT ON TABLE ATTENDANCE IS '출결 관리';
   COMMENT ON COLUMN ATTENDANCE.ATTENDANCE_DATE IS '출결 일자';  
   COMMENT ON COLUMN ATTENDANCE.ATTENDANCE_SEQ IS '등록 번호';
   COMMENT ON COLUMN ATTENDANCE.ATTENDANCE_TYPE IS '출결 정보';
   COMMENT ON COLUMN ATTENDANCE.ATTENDANCE_STATUS IS '출결 상태'; 
   COMMENT ON COLUMN ATTENDANCE.USER_CD IS '유저 코드'; 
   COMMENT ON COLUMN ATTENDANCE.ATTENDANCE_REG_DATE IS '출결 등록일'; 
   COMMENT ON COLUMN ATTENDANCE.ATTENDANCE_UPD_DATE IS '출결 수정일';
   COMMENT ON COLUMN ATTENDANCE.ATTENDANCE_DEL_DATE IS '출결 삭제일';
   COMMENT ON COLUMN ATTENDANCE.ATTENDANCE_UPD_CNT IS '출결 수정 횟수'; 
   COMMENT ON COLUMN ATTENDANCE.ATTENDANCE_DEL_CNT IS '출결 삭제 횟수'; 
   COMMENT ON COLUMN ATTENDANCE.LATITUDE IS '위도'; 
   COMMENT ON COLUMN ATTENDANCE.LONGITUDE IS '경도';
   COMMENT ON COLUMN ATTENDANCE.PLACE_INFO IS '현재 위치 정보';
   COMMENT ON COLUMN ATTENDANCE.TERMINAL IS '단말기'; 
   COMMENT ON COLUMN ATTENDANCE.ERROR_CD IS '에러 코드'; 
   COMMENT ON COLUMN ATTENDANCE.ERROR_MSG IS '에러 메시지'; 
   COMMENT ON COLUMN ATTENDANCE.REMARK IS '비고'; 
   COMMENT ON COLUMN ATTENDANCE.REGIST_USER IS '등록 유저';
   COMMENT ON COLUMN ATTENDANCE.REGIST_DATE IS '등록일';
   COMMENT ON COLUMN ATTENDANCE.UPDATE_USER IS '수정 유저';
   COMMENT ON COLUMN ATTENDANCE.UPDATE_DATE IS '수정일';
   COMMENT ON COLUMN ATTENDANCE.UPDATE_CNT IS '수정 횟수';
   COMMENT ON COLUMN ATTENDANCE.DEL_FLG IS '삭제 플래그';