  CREATE TABLE LOGIC_SERVICE
   (RESULT_SEQ VARCHAR2(100),
    SERVICE_NAME VARCHAR2(30), 
    ENCRYPT_RES_DATA CLOB,
    STATUS VARCHAR2(2),
    USER_CD VARCHAR2(10),
    ERROR_CD VARCHAR2(30),
    ERROR_MSG VARCHAR2(500),
    REGIST_USER VARCHAR2(10), 
    REGIST_DATE DATE DEFAULT SYSDATE, 
    UPDATE_USER VARCHAR2(10), 
    UPDATE_DATE DATE DEFAULT SYSDATE, 
    UPDATE_CNT NUMBER(10,0) DEFAULT 0, 
    DEL_FLG VARCHAR2(1) DEFAULT '0',
   CONSTRAINT LOGIC_SERVICE_PK PRIMARY KEY (RESULT_SEQ)
  );

   COMMENT ON TABLE LOGIC_SERVICE IS '서비스 관리';
   COMMENT ON COLUMN LOGIC_SERVICE.RESULT_SEQ IS '결과 값';  
   COMMENT ON COLUMN LOGIC_SERVICE.SERVICE_NAME IS '서비스 명';
   COMMENT ON COLUMN LOGIC_SERVICE.ENCRYPT_RES_DATA IS '응답 데이터 암호화';
   COMMENT ON COLUMN LOGIC_SERVICE.STATUS IS '상태'; 
   COMMENT ON COLUMN LOGIC_SERVICE.USER_CD IS '유저 코드'; 
   COMMENT ON COLUMN LOGIC_SERVICE.ERROR_CD IS '에러 코드'; 
   COMMENT ON COLUMN LOGIC_SERVICE.ERROR_MSG IS '에러 메시지';
   COMMENT ON COLUMN LOGIC_SERVICE.REGIST_USER IS '등록 유저';
   COMMENT ON COLUMN LOGIC_SERVICE.REGIST_DATE IS '등록일';
   COMMENT ON COLUMN LOGIC_SERVICE.UPDATE_USER IS '수정 유저';
   COMMENT ON COLUMN LOGIC_SERVICE.UPDATE_DATE IS '수정일';
   COMMENT ON COLUMN LOGIC_SERVICE.UPDATE_CNT IS '수정 횟수';
   COMMENT ON COLUMN LOGIC_SERVICE.DEL_FLG IS '삭제 플래그';