  CREATE TABLE DEPART_MST 
   (DEPART_CD VARCHAR2(10),
    DEPART_NAME VARCHAR2(50), 
    DEPART_RANK NUMBER(2),
    DEPART_REG_DATE DATE DEFAULT SYSDATE,
    DEPART_DEL_DATE DATE,
    DEPART_STATUS VARCHAR2(2) DEFAULT '0',
    REGIST_USER VARCHAR2(10), 
    REGIST_DATE DATE DEFAULT SYSDATE, 
    UPDATE_USER VARCHAR2(10), 
    UPDATE_DATE DATE DEFAULT SYSDATE, 
    UPDATE_CNT NUMBER(10,0) DEFAULT 0, 
    DEL_FLG VARCHAR2(1) DEFAULT '0', 
   CONSTRAINT DEPART_MST_PK PRIMARY KEY (DEPART_CD) 
  );

   COMMENT ON COLUMN DEPART_MST.DEPART_CD IS '부서 코드';  
   COMMENT ON COLUMN DEPART_MST.DEPART_NAME IS '부서 이름';
   COMMENT ON COLUMN DEPART_MST.DEPART_RANK IS '부서 등급';
   COMMENT ON COLUMN DEPART_MST.DEPART_REG_DATE IS '부서 가입일'; 
   COMMENT ON COLUMN DEPART_MST.DEPART_DEL_DATE IS '부서 삭제일'; 
   COMMENT ON COLUMN DEPART_MST.DEPART_STATUS IS '부서 상태'; 
   COMMENT ON COLUMN DEPART_MST.REGIST_USER IS '등록 유저';
   COMMENT ON COLUMN DEPART_MST.REGIST_DATE IS '등록일';
   COMMENT ON COLUMN DEPART_MST.UPDATE_USER IS '수정 유저';
   COMMENT ON COLUMN DEPART_MST.UPDATE_DATE IS '수정일';
   COMMENT ON COLUMN DEPART_MST.UPDATE_CNT IS '수정 횟수';
   COMMENT ON COLUMN DEPART_MST.DEL_FLG IS '삭제 플래그';