-- =========================================================
-- V5: SaaS 전환 화면 UI 텍스트 시드 (한/영/일)
-- 구성: 관리 화면(W999/W001/W007/W008/W009 — frontend-plan §7 정본)
--       + 랜딩(W000 LANDING_* — landing-page.md §2 정본)
-- INSERT IGNORE: 관리자가 이미 등록/수정한 키는 덮어쓰지 않는다(V3 방식).
-- 폐기 키 DELETE 없음: V3 시드의 W003 전 행·W999/SIGNUP·W000/INDEX_*는
--   어떤 화면도 참조하지 않는 무해한 잔존으로 허용(W003 코드는 영구 결번).
-- =========================================================

INSERT IGNORE INTO language_master (window_id, lang_key, lang, lang_value) VALUES
-- ---- W999 ----
('W999','TENANT_CODE','KOR','회사 코드'),
('W999','TENANT_CODE','ENG','Company code'),
('W999','TENANT_CODE','JPN','会社コード'),
('W999','TENANTS','KOR','테넌트'),
('W999','TENANTS','ENG','Tenants'),
('W999','TENANTS','JPN','テナント'),
('W999','MEMBERS','KOR','멤버'),
('W999','MEMBERS','ENG','Members'),
('W999','MEMBERS','JPN','メンバー'),
('W999','EDIT','KOR','수정'),
('W999','EDIT','ENG','Edit'),
('W999','EDIT','JPN','編集'),
('W999','CLOSE','KOR','닫기'),
('W999','CLOSE','ENG','Close'),
('W999','CLOSE','JPN','閉じる'),
('W999','COPY','KOR','복사'),
('W999','COPY','ENG','Copy'),
('W999','COPY','JPN','コピー'),
('W999','STATUS','KOR','상태'),
('W999','STATUS','ENG','Status'),
('W999','STATUS','JPN','状態'),
-- ---- W000 ----
('W000','LANDING_HERO_BADGE','KOR','중소기업을 위한 근태 관리 SaaS'),
('W000','LANDING_HERO_BADGE','ENG','Attendance SaaS for small & mid-sized teams'),
('W000','LANDING_HERO_BADGE','JPN','中小企業向け勤怠管理SaaS'),
('W000','LANDING_HERO_TITLE','KOR','출근의 순간을, 신뢰할 수 있는 기록으로'),
('W000','LANDING_HERO_TITLE','ENG','Turn every clock-in into a record you can trust'),
('W000','LANDING_HERO_TITLE','JPN','出退勤の瞬間を、信頼できる記録に'),
('W000','LANDING_HERO_SUB','KOR','위치 기반 출결과 2단계 변조 탐지로 근태 기록의 신뢰를 지킵니다. 별도 설치 없이 웹 브라우저에서 바로 사용하는 기업용 출결 시스템입니다.'),
('W000','LANDING_HERO_SUB','ENG','Location-based check-in and two-step tamper detection keep your attendance records trustworthy. A web-based attendance system for companies — no installation required.'),
('W000','LANDING_HERO_SUB','JPN','位置情報にもとづく打刻と2段階の改ざん検知で、勤怠記録の信頼性を守ります。インストール不要、Webブラウザだけで使える企業向け勤怠システムです。'),
('W000','LANDING_FEATURES_TITLE','KOR','핵심 기능'),
('W000','LANDING_FEATURES_TITLE','ENG','Key features'),
('W000','LANDING_FEATURES_TITLE','JPN','主な機能'),
('W000','LANDING_FEAT1_TITLE','KOR','위치 기반 출결'),
('W000','LANDING_FEAT1_TITLE','ENG','Location-based clock-in'),
('W000','LANDING_FEAT1_TITLE','JPN','位置情報にもとづく打刻'),
('W000','LANDING_FEAT1_DESC','KOR','출근·퇴근·조퇴·휴식을 위치 정보와 함께 기록합니다. 어디에서 남긴 기록인지가 근태 데이터에 그대로 남습니다.'),
('W000','LANDING_FEAT1_DESC','ENG','Record clock-in, clock-out, early leave, and breaks together with location data. Where each stamp was made stays part of the attendance record.'),
('W000','LANDING_FEAT1_DESC','JPN','出勤・退勤・早退・休憩を位置情報とともに記録します。どこで打刻されたかが、勤怠データにそのまま残ります。'),
('W000','LANDING_FEAT2_TITLE','KOR','체크 → 확정, 2단계 변조 탐지'),
('W000','LANDING_FEAT2_TITLE','ENG','Two-step tamper detection'),
('W000','LANDING_FEAT2_TITLE','JPN','チェック→確定、2段階の改ざん検知'),
('W000','LANDING_FEAT2_DESC','KOR','출결은 체크와 확정 두 단계로 처리되고, 두 시점의 데이터를 해시로 대조해 중간 변조를 탐지합니다. 조작된 요청은 기록으로 남지 않습니다.'),
('W000','LANDING_FEAT2_DESC','ENG','Every stamp goes through a check step and a confirm step, compared with a cryptographic hash. Requests altered in between are rejected before they ever become records.'),
('W000','LANDING_FEAT2_DESC','JPN','打刻はチェックと確定の2段階で処理され、両時点のデータをハッシュで照合して改ざんを検知します。改変されたリクエストは記録として残りません。'),
('W000','LANDING_FEAT3_TITLE','KOR','월별 근태 상세'),
('W000','LANDING_FEAT3_TITLE','ENG','Monthly attendance detail'),
('W000','LANDING_FEAT3_TITLE','JPN','月別勤怠詳細'),
('W000','LANDING_FEAT3_DESC','KOR','일자별 근무 스케줄과 실제 출퇴근 시각을 한 화면에서 확인합니다. 야간 근무 표기, 개인별 근무시간, 공휴일까지 반영된 월별 뷰를 제공합니다.'),
('W000','LANDING_FEAT3_DESC','ENG','See each day''s work schedule and actual clock-in/out times in a single view. Overnight work, per-person schedules, and company holidays are all reflected in the monthly view.'),
('W000','LANDING_FEAT3_DESC','JPN','日ごとの勤務スケジュールと実際の出退勤時刻を1つの画面で確認できます。深夜勤務の表記、個人別の勤務時間、休日まで反映した月別ビューを提供します。'),
('W000','LANDING_FEAT4_TITLE','KOR','한국어·영어·일본어 지원'),
('W000','LANDING_FEAT4_TITLE','ENG','Korean, English, and Japanese'),
('W000','LANDING_FEAT4_TITLE','JPN','日本語・英語・韓国語に対応'),
('W000','LANDING_FEAT4_DESC','KOR','화면과 안내 메시지가 사용자가 선택한 언어로 표시됩니다. 다국적 구성원이 있는 팀도 같은 시스템을 함께 사용할 수 있습니다.'),
('W000','LANDING_FEAT4_DESC','ENG','Screens and messages are shown in the language each user selects. Teams with members from different countries can share one system.'),
('W000','LANDING_FEAT4_DESC','JPN','画面や案内メッセージが、ユーザーの選んだ言語で表示されます。多国籍のメンバーがいるチームでも、同じシステムを一緒に使えます。'),
('W000','LANDING_TRUST_TITLE','KOR','기업 데이터를 지키는 기본기'),
('W000','LANDING_TRUST_TITLE','ENG','Built to protect your company''s data'),
('W000','LANDING_TRUST_TITLE','JPN','企業データを守る基本設計'),
('W000','LANDING_TRUST1_TITLE','KOR','기업별 데이터 격리'),
('W000','LANDING_TRUST1_TITLE','ENG','Per-company data isolation'),
('W000','LANDING_TRUST1_TITLE','JPN','企業ごとのデータ分離'),
('W000','LANDING_TRUST1_DESC','KOR','고객사마다 분리된 계정 체계로 운영되어 다른 회사의 데이터에는 접근할 수 없습니다. 운영자도 고객사 내부의 출결 데이터는 열람하지 않는 것을 원칙으로 합니다.'),
('W000','LANDING_TRUST1_DESC','ENG','Each company operates on its own isolated account scope — no one can reach another company''s data. As a policy, even the service operator does not view attendance data inside a customer''s workspace.'),
('W000','LANDING_TRUST1_DESC','JPN','顧客企業ごとに分離されたアカウント体系で運用され、他社のデータにはアクセスできません。運営者であっても、顧客企業内の勤怠データは閲覧しないことを原則としています。'),
('W000','LANDING_TRUST2_TITLE','KOR','안전한 인증'),
('W000','LANDING_TRUST2_TITLE','ENG','Secure authentication'),
('W000','LANDING_TRUST2_TITLE','JPN','安全な認証'),
('W000','LANDING_TRUST2_DESC','KOR','비밀번호는 복호화할 수 없는 BCrypt 해시로만 저장합니다. 로그인 실패 응답은 계정 존재 여부를 노출하지 않도록 설계되어 있으며, 관리자 권한은 일반 사용자와 분리되어 있습니다.'),
('W000','LANDING_TRUST2_DESC','ENG','Passwords are stored only as irreversible BCrypt hashes. Failed logins never reveal whether an account exists, and administrator privileges are kept separate from regular users.'),
('W000','LANDING_TRUST2_DESC','JPN','パスワードは復号できないBCryptハッシュとしてのみ保存します。ログイン失敗時の応答はアカウントの有無を明かさない設計で、管理者権限は一般ユーザーと分離されています。'),
('W000','LANDING_TRUST3_TITLE','KOR','기록의 무결성'),
('W000','LANDING_TRUST3_TITLE','ENG','Integrity of every record'),
('W000','LANDING_TRUST3_TITLE','JPN','記録の完全性'),
('W000','LANDING_TRUST3_DESC','KOR','모든 출결은 체크 시점의 데이터와 해시로 대조된 뒤에만 확정됩니다. 확정 이후의 기록은 시각·위치·단말 정보와 함께 보관됩니다.'),
('W000','LANDING_TRUST3_DESC','ENG','An attendance record is finalized only after it matches the hash of its check step. Once confirmed, each record is kept with its time, location, and device information.'),
('W000','LANDING_TRUST3_DESC','JPN','すべての打刻は、チェック時点のデータとハッシュで照合された後にのみ確定されます。確定後の記録は、時刻・位置・端末情報とともに保管されます。'),
('W000','LANDING_STEPS_TITLE','KOR','도입 절차'),
('W000','LANDING_STEPS_TITLE','ENG','How to get started'),
('W000','LANDING_STEPS_TITLE','JPN','ご導入の流れ'),
('W000','LANDING_STEP1_TITLE','KOR','1. 도입 문의'),
('W000','LANDING_STEP1_TITLE','ENG','1. Contact us'),
('W000','LANDING_STEP1_TITLE','JPN','1. お問い合わせ'),
('W000','LANDING_STEP1_DESC','KOR','이메일로 회사명과 인원 규모를 보내 주세요. 도입 범위와 일정을 안내해 드립니다.'),
('W000','LANDING_STEP1_DESC','ENG','Send us your company name and team size by email. We will get back to you with scope and schedule.'),
('W000','LANDING_STEP1_DESC','JPN','メールで会社名とご利用人数をお知らせください。導入範囲とスケジュールをご案内します。'),
('W000','LANDING_STEP2_TITLE','KOR','2. 회사 계정 발급'),
('W000','LANDING_STEP2_TITLE','ENG','2. Workspace setup'),
('W000','LANDING_STEP2_TITLE','JPN','2. アカウント発行'),
('W000','LANDING_STEP2_DESC','KOR','계약이 확정되면 운영팀이 귀사 전용 공간과 관리자 계정을 만들어 드립니다. 별도의 설치나 서버 준비는 필요 없습니다.'),
('W000','LANDING_STEP2_DESC','ENG','Once the contract is set, our team creates your company workspace and an administrator account. No installation or servers on your side.'),
('W000','LANDING_STEP2_DESC','JPN','ご契約後、運営チームが貴社専用のワークスペースと管理者アカウントを作成します。インストールやサーバーの準備は不要です。'),
('W000','LANDING_STEP3_TITLE','KOR','3. 구성원 등록 후 바로 사용'),
('W000','LANDING_STEP3_TITLE','ENG','3. Add members and go'),
('W000','LANDING_STEP3_TITLE','JPN','3. メンバー登録してすぐ利用'),
('W000','LANDING_STEP3_DESC','KOR','관리자가 구성원을 등록하면 그날부터 웹 브라우저에서 출결 기록을 시작할 수 있습니다.'),
('W000','LANDING_STEP3_DESC','ENG','As soon as your administrator adds members, everyone can start recording attendance in the browser.'),
('W000','LANDING_STEP3_DESC','JPN','管理者がメンバーを登録すれば、その日からWebブラウザで勤怠記録を始められます。'),
('W000','LANDING_CTA_TITLE','KOR','팀의 근태 관리, 지금 시작하세요'),
('W000','LANDING_CTA_TITLE','ENG','Start managing attendance the reliable way'),
('W000','LANDING_CTA_TITLE','JPN','チームの勤怠管理を、今すぐ'),
('W000','LANDING_CTA_SUB','KOR','도입 문의를 보내 주시면 하루 안에 회신드립니다.'),
('W000','LANDING_CTA_SUB','ENG','Send an inquiry and we will reply within one business day.'),
('W000','LANDING_CTA_SUB','JPN','お問い合わせいただければ、1営業日以内にご返信します。'),
('W000','LANDING_CTA_CONTACT','KOR','도입 문의하기'),
('W000','LANDING_CTA_CONTACT','ENG','Contact us'),
('W000','LANDING_CTA_CONTACT','JPN','導入のお問い合わせ'),
('W000','LANDING_CTA_LOGIN','KOR','로그인'),
('W000','LANDING_CTA_LOGIN','ENG','Log in'),
('W000','LANDING_CTA_LOGIN','JPN','ログイン'),
('W000','LANDING_FOOTER_PRODUCT','KOR','Web Attendance — 웹 출결 관리 시스템'),
('W000','LANDING_FOOTER_PRODUCT','ENG','Web Attendance — web-based attendance management'),
('W000','LANDING_FOOTER_PRODUCT','JPN','Web Attendance — Web勤怠管理システム'),
('W000','LANDING_FOOTER_CONTACT','KOR','도입 문의: {CONTACT_EMAIL}'),
('W000','LANDING_FOOTER_CONTACT','ENG','Sales inquiries: {CONTACT_EMAIL}'),
('W000','LANDING_FOOTER_CONTACT','JPN','導入に関するお問い合わせ: {CONTACT_EMAIL}'),
('W000','LANDING_FOOTER_COPYRIGHT','KOR','© 2026 Web Attendance. All rights reserved.'),
('W000','LANDING_FOOTER_COPYRIGHT','ENG','© 2026 Web Attendance. All rights reserved.'),
('W000','LANDING_FOOTER_COPYRIGHT','JPN','© 2026 Web Attendance. All rights reserved.'),
('W000','CONTACT_EMAIL','KOR','sales@webatt.example'),
('W000','CONTACT_EMAIL','ENG','sales@webatt.example'),
('W000','CONTACT_EMAIL','JPN','sales@webatt.example'),
-- ---- W001 ----
('W001','TENANT_CODE_HINT','KOR','회사에서 안내받은 코드를 입력하세요.'),
('W001','TENANT_CODE_HINT','ENG','Enter the code provided by your company.'),
('W001','TENANT_CODE_HINT','JPN','会社から案内されたコードを入力してください。'),
-- ---- W007 ----
('W007','TENANTS_TITLE','KOR','테넌트 관리'),
('W007','TENANTS_TITLE','ENG','Tenant management'),
('W007','TENANTS_TITLE','JPN','テナント管理'),
('W007','TENANT_CREATE','KOR','테넌트 생성'),
('W007','TENANT_CREATE','ENG','Create tenant'),
('W007','TENANT_CREATE','JPN','テナント作成'),
('W007','TENANT_NAME','KOR','회사명'),
('W007','TENANT_NAME','ENG','Company name'),
('W007','TENANT_NAME','JPN','会社名'),
('W007','ADMIN_EMAIL','KOR','관리자 이메일'),
('W007','ADMIN_EMAIL','ENG','Admin email'),
('W007','ADMIN_EMAIL','JPN','管理者メール'),
('W007','ADMIN_NAME','KOR','관리자 이름'),
('W007','ADMIN_NAME','ENG','Admin name'),
('W007','ADMIN_NAME','JPN','管理者名'),
('W007','MEMBER_COUNT','KOR','멤버 수'),
('W007','MEMBER_COUNT','ENG','Members'),
('W007','MEMBER_COUNT','JPN','メンバー数'),
('W007','CREATED_AT','KOR','생성일'),
('W007','CREATED_AT','ENG','Created'),
('W007','CREATED_AT','JPN','作成日'),
('W007','TENANT_STATUS_ACTIVE','KOR','사용 중'),
('W007','TENANT_STATUS_ACTIVE','ENG','Active'),
('W007','TENANT_STATUS_ACTIVE','JPN','利用中'),
('W007','TENANT_STATUS_SUSPENDED','KOR','정지'),
('W007','TENANT_STATUS_SUSPENDED','ENG','Suspended'),
('W007','TENANT_STATUS_SUSPENDED','JPN','停止'),
('W007','SUSPEND','KOR','정지'),
('W007','SUSPEND','ENG','Suspend'),
('W007','SUSPEND','JPN','停止'),
('W007','RESUME','KOR','재개'),
('W007','RESUME','ENG','Resume'),
('W007','RESUME','JPN','再開'),
('W007','DETAIL','KOR','상세'),
('W007','DETAIL','ENG','Detail'),
('W007','DETAIL','JPN','詳細'),
('W007','INITIAL_PWD','KOR','초기 비밀번호'),
('W007','INITIAL_PWD','ENG','Initial password'),
('W007','INITIAL_PWD','JPN','初期パスワード'),
('W007','INITIAL_PWD_NOTE','KOR','이 비밀번호는 지금만 표시되며 다시 조회할 수 없습니다. 안전한 경로로 전달하세요.'),
('W007','INITIAL_PWD_NOTE','ENG','This password is shown only once and cannot be retrieved again. Share it securely.'),
('W007','INITIAL_PWD_NOTE','JPN','このパスワードは今回のみ表示され、再照会できません。安全な方法で共有してください。'),
-- ---- W008 ----
('W008','PROFILE_TITLE','KOR','기업 정보'),
('W008','PROFILE_TITLE','ENG','Company profile'),
('W008','PROFILE_TITLE','JPN','企業情報'),
('W008','BILLING_TITLE','KOR','결제 정보'),
('W008','BILLING_TITLE','ENG','Billing'),
('W008','BILLING_TITLE','JPN','請求情報'),
('W008','BIZ_REG_NO','KOR','사업자등록번호'),
('W008','BIZ_REG_NO','ENG','Business reg. no.'),
('W008','BIZ_REG_NO','JPN','事業者登録番号'),
('W008','CEO_NAME','KOR','대표자명'),
('W008','CEO_NAME','ENG','CEO name'),
('W008','CEO_NAME','JPN','代表者名'),
('W008','ADDRESS','KOR','주소'),
('W008','ADDRESS','ENG','Address'),
('W008','ADDRESS','JPN','住所'),
('W008','CONTACT_NAME','KOR','담당자'),
('W008','CONTACT_NAME','ENG','Contact name'),
('W008','CONTACT_NAME','JPN','担当者'),
('W008','CONTACT_EMAIL','KOR','담당자 이메일'),
('W008','CONTACT_EMAIL','ENG','Contact email'),
('W008','CONTACT_EMAIL','JPN','担当者メール'),
('W008','CONTACT_PHONE','KOR','담당자 연락처'),
('W008','CONTACT_PHONE','ENG','Contact phone'),
('W008','CONTACT_PHONE','JPN','担当者電話番号'),
('W008','BILLING_METHOD','KOR','결제 방식'),
('W008','BILLING_METHOD','ENG','Billing method'),
('W008','BILLING_METHOD','JPN','支払方法'),
('W008','METHOD_INVOICE','KOR','세금계산서/계좌이체'),
('W008','METHOD_INVOICE','ENG','Invoice / bank transfer'),
('W008','METHOD_INVOICE','JPN','請求書/口座振込'),
('W008','METHOD_CARD','KOR','카드(빌링키)'),
('W008','METHOD_CARD','ENG','Card (billing key)'),
('W008','METHOD_CARD','JPN','カード（ビリングキー）'),
('W008','BILLING_EMAIL','KOR','청구서 수신 이메일'),
('W008','BILLING_EMAIL','ENG','Billing email'),
('W008','BILLING_EMAIL','JPN','請求書送付先メール'),
('W008','BILLING_KEY','KOR','PG 빌링키'),
('W008','BILLING_KEY','ENG','PG billing key'),
('W008','BILLING_KEY','JPN','PGビリングキー'),
('W008','BILLING_KEY_SET','KOR','등록됨'),
('W008','BILLING_KEY_SET','ENG','Registered'),
('W008','BILLING_KEY_SET','JPN','登録済み'),
('W008','BILLING_KEY_UNSET','KOR','미등록'),
('W008','BILLING_KEY_UNSET','ENG','Not registered'),
('W008','BILLING_KEY_UNSET','JPN','未登録'),
('W008','CARD_LAST4','KOR','카드 마지막 4자리'),
('W008','CARD_LAST4','ENG','Card last 4 digits'),
('W008','CARD_LAST4','JPN','カード下4桁'),
('W008','CARD_BRAND','KOR','카드 브랜드'),
('W008','CARD_BRAND','ENG','Card brand'),
('W008','CARD_BRAND','JPN','カードブランド'),
('W008','PLAN','KOR','플랜'),
('W008','PLAN','ENG','Plan'),
('W008','PLAN','JPN','プラン'),
('W008','BILLED_FROM','KOR','과금 시작일'),
('W008','BILLED_FROM','ENG','Billed from'),
('W008','BILLED_FROM','JPN','課金開始日'),
('W008','MEMO','KOR','메모'),
('W008','MEMO','ENG','Memo'),
('W008','MEMO','JPN','メモ'),
('W008','NOT_REGISTERED','KOR','아직 등록된 정보가 없습니다.'),
('W008','NOT_REGISTERED','ENG','Nothing registered yet.'),
('W008','NOT_REGISTERED','JPN','まだ登録された情報はありません。'),
('W008','REENTER_NOTE','KOR','수정 시 모든 항목을 다시 입력합니다. 저장된 값은 표시되지 않습니다.'),
('W008','REENTER_NOTE','ENG','Editing requires re-entering every field. Stored values are never shown.'),
('W008','REENTER_NOTE','JPN','修正時はすべての項目を再入力します。保存済みの値は表示されません。'),
('W008','UPDATED_AT','KOR','수정일'),
('W008','UPDATED_AT','ENG','Updated'),
('W008','UPDATED_AT','JPN','更新日'),
-- ---- W009 ----
('W009','MEMBERS_TITLE','KOR','멤버 관리'),
('W009','MEMBERS_TITLE','ENG','Member management'),
('W009','MEMBERS_TITLE','JPN','メンバー管理'),
('W009','MEMBER_CREATE','KOR','멤버 등록'),
('W009','MEMBER_CREATE','ENG','Add member'),
('W009','MEMBER_CREATE','JPN','メンバー登録'),
('W009','NAME','KOR','이름'),
('W009','NAME','ENG','Name'),
('W009','NAME','JPN','名前'),
('W009','DEPART','KOR','부서 코드(선택)'),
('W009','DEPART','ENG','Department code (optional)'),
('W009','DEPART','JPN','部署コード（任意）'),
('W009','ROLE','KOR','역할'),
('W009','ROLE','ENG','Role'),
('W009','ROLE','JPN','役割'),
('W009','ROLE_TENANT_ADMIN','KOR','관리자'),
('W009','ROLE_TENANT_ADMIN','ENG','Admin'),
('W009','ROLE_TENANT_ADMIN','JPN','管理者'),
('W009','ROLE_MEMBER','KOR','멤버'),
('W009','ROLE_MEMBER','ENG','Member'),
('W009','ROLE_MEMBER','JPN','メンバー'),
('W009','STATUS_ACTIVE','KOR','사용 중'),
('W009','STATUS_ACTIVE','ENG','Active'),
('W009','STATUS_ACTIVE','JPN','利用中'),
('W009','STATUS_DISABLED','KOR','비활성'),
('W009','STATUS_DISABLED','ENG','Disabled'),
('W009','STATUS_DISABLED','JPN','無効'),
('W009','STATUS_PENDING','KOR','대기'),
('W009','STATUS_PENDING','ENG','Pending'),
('W009','STATUS_PENDING','JPN','保留'),
('W009','DISABLE','KOR','비활성'),
('W009','DISABLE','ENG','Disable'),
('W009','DISABLE','JPN','無効化'),
('W009','ENABLE','KOR','활성화'),
('W009','ENABLE','ENG','Enable'),
('W009','ENABLE','JPN','有効化'),
('W009','PROMOTE','KOR','관리자 지정'),
('W009','PROMOTE','ENG','Make admin'),
('W009','PROMOTE','JPN','管理者に設定'),
('W009','DEMOTE','KOR','관리자 해제'),
('W009','DEMOTE','ENG','Revoke admin'),
('W009','DEMOTE','JPN','管理者を解除'),
('W009','INITIAL_PWD','KOR','초기 비밀번호'),
('W009','INITIAL_PWD','ENG','Initial password'),
('W009','INITIAL_PWD','JPN','初期パスワード'),
('W009','INITIAL_PWD_NOTE','KOR','이 비밀번호는 지금만 표시되며 다시 조회할 수 없습니다. 본인에게 안전하게 전달하세요.'),
('W009','INITIAL_PWD_NOTE','ENG','This password is shown only once and cannot be retrieved again. Share it with the member securely.'),
('W009','INITIAL_PWD_NOTE','JPN','このパスワードは今回のみ表示され、再照会できません。本人へ安全に共有してください。');
