CREATE TABLE SCHEDULE_MANAGEMENT 
   (USER_CD VARCHAR2(10),
    SCHEDULE_CD VARCHAR2(10),
    SCHEDULE_DATE DATE, 
    SCHEDULE_START_TIME VARCHAR2(10),
    SCHEDULE_END_TIME VARCHAR2(10), 
    HOLIDAY_SEQ NUMBER(11),
    ADMIN_APPROVE NUMBER(1) DEFAULT 0, 
    REGIST_USER VARCHAR2(10), 
    REGIST_DATE DATE DEFAULT SYSDATE, 
    UPDATE_USER VARCHAR2(10), 
    UPDATE_DATE DATE DEFAULT SYSDATE, 
    UPDATE_CNT NUMBER(10,0) DEFAULT 0, 
    DEL_FLG VARCHAR2(1) DEFAULT '0', 
   CONSTRAINT SCHEDULE_MANAGEMENT_PK PRIMARY KEY (SCHEDULE_CD, USER_CD),
   CONSTRAINT SM_USER_FK FOREIGN KEY(USER_CD) REFERENCES USER_MST(USER_CD) ON DELETE CASCADE,
   CONSTRAINT SM_HOLI_FK FOREIGN KEY(HOLIDAY_SEQ) REFERENCES HOLIDAY_VALUES(HOLIDAY_SEQ) ON DELETE CASCADE
  );

   COMMENT ON TABLE SCHEDULE_MANAGEMENT IS '스케쥴 관리';
   COMMENT ON COLUMN SCHEDULE_MANAGEMENT.USER_CD IS '유저 코드';  
   COMMENT ON COLUMN SCHEDULE_MANAGEMENT.SCHEDULE_CD IS '스케쥴 관리 코드';  
   COMMENT ON COLUMN SCHEDULE_MANAGEMENT.SCHEDULE_DATE IS '스케쥴 적용 날짜';
   COMMENT ON COLUMN SCHEDULE_MANAGEMENT.SCHEDULE_START_TIME IS '스케쥴 시작 시간';
   COMMENT ON COLUMN SCHEDULE_MANAGEMENT.SCHEDULE_END_TIME IS '스케쥴 끝나는 시간';
   COMMENT ON COLUMN SCHEDULE_MANAGEMENT.HOLIDAY_SEQ IS '휴가 종류';
   COMMENT ON COLUMN SCHEDULE_MANAGEMENT.ADMIN_APPROVE IS '관리자 승인';
   COMMENT ON COLUMN SCHEDULE_MANAGEMENT.REGIST_USER IS '등록 유저';
   COMMENT ON COLUMN SCHEDULE_MANAGEMENT.REGIST_DATE IS '등록일';
   COMMENT ON COLUMN SCHEDULE_MANAGEMENT.UPDATE_USER IS '수정 유저';
   COMMENT ON COLUMN SCHEDULE_MANAGEMENT.UPDATE_DATE IS '수정일';
   COMMENT ON COLUMN SCHEDULE_MANAGEMENT.UPDATE_CNT IS '수정 횟수';
   COMMENT ON COLUMN SCHEDULE_MANAGEMENT.DEL_FLG IS '삭제 플래그';